#!/usr/bin/env node
/**
 * Injects runtime environment variables into the Next.js app.
 * This allows the local script to override the API base URL at runtime.
 */

const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, '..', 'public');
const envJsPath = path.join(publicDir, 'env.js');

// Ensure public directory exists
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

// Get the API base URL from environment or use default
const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://api.zexy.live';

// Create the env.js file with runtime configuration
const envContent = `
// Runtime environment configuration
// This file is generated by scripts/inject-env.js
window.__NEXT_PUBLIC_API_BASE_URL__ = '${apiBaseUrl}';
console.log('[API] Runtime Base URL:', '${apiBaseUrl}');
`;

fs.writeFileSync(envJsPath, envContent.trim());
console.log(`[ENV] Environment injected: API_BASE_URL=${apiBaseUrl}`);
